### ISSUE TITLE
[Support] Need help reducing GPU memory usage.

### ISSUE THREAD

**Issue by sequoia-hope** [PRBonn/bonnetal#20]
Hello!

Nice looking library! I'd like to train mobilenetv2 for semantic segmentation using my coco-like dataset. I've copied the coco dataloader and updated things for my data.

But even though my GPU has 16GB of ram and I've set batch size to 1, I'm still consuming all my GPU memory as soon as training begins, crashing the session.

My config is below, followed by a dump of my terminal output. I'm not sure what I'm doing wrong.
```
#training parameters
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 1000
  max_lr: 0.005          # sgd learning rate max
  min_lr: 0.001          # warmup initial learning rate
  up_epochs: 1           # warmup during first XX epochs (can be float)
  down_epochs:  20       # warmdown during second XX epochs  (can be float)
  max_momentum: 0.7      # sgd momentum max when lr is mim
  min_momentum: 0.5      # sgd momentum min when lr is max
  final_decay: 0.95      # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size:  1         # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  save_summary: False    # Summary of weight histograms for tensorboard
  save_imgs: False        # False doesn't save anything, True saves some
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  avg_N: 3               # average the N best models
  crop_prop:
    width: 2560
    height: 1440

# backbone parameters
backbone:
  name: "mobilenetv2"
  dropout: 0.01
  bn_d: 0.01
  OS: 8  # output stride
  train: True # train backbone?
  extra:
    width_mult: 1.0
    shallow_feats: True # get features before the last layer (mn2)

decoder:
  name: "aspp_residual"
  dropout: 0.01
  bn_d: 0.01
  train: True # train decoder?
  extra:
    aspp_channels: 64
    skip_os: [4]
    last_channels: 32

# classification head parameters
head:
  name: "segmentation"
  dropout: 0.01

# dataset (to find parser)
dataset:
  name: "rover"
  location: "/home/taylor/datasets/rover"
  workers: 1  # number of threads to get data
  img_means: #rgb
    - 0.47037394
    - 0.44669544
    - 0.40731883
  img_stds: #rgb
    - 0.27876515
    - 0.27429348
    - 0.28861644
  img_prop:
    width: 2560
    height: 1440
    depth: 3
  labels:
    0: 'nothing'
    1: 'trail'
    2: 'terrain'
    3: 'sidewalk'
    4: 'person'
    5: 'traffic_cone'
    6: 'vehicle'
    7: 'private_road'
    8: 'dirt_road'
    9: 'drivable_ground'
    10: 'building'
    11: 'public_street'
  labels_w:
    0: 1.0
    1: 1.0
    2: 1.0
    3: 1.0
    4: 1.0
    5: 1.0
    6: 1.0
    7: 1.0
    8: 1.0
    9: 1.0
    10: 1.0
    11: 1.0
  color_map: # bgr
    0: [0, 0, 0]
    1: [220, 20, 60]
    2: [119, 11, 32]
    3: [0, 0, 142]
    4: [0, 0, 230]
    5: [106, 0, 228]
    6: [0, 60, 100]
    7: [0, 80, 100]
    8: [0, 0, 70]
    9: [0, 0, 192]
    10: [250, 170, 30]
    11: [100, 170, 30]

```

Here is my terminal output (There's a few extra things being printed due to some debugging):

```
developer@taylor-desktop:~/bonnetal/train/tasks/segmentation$ ./train.py --cfg config/rover/mobilenetv2_aspp_res.yaml 
----------
INTERFACE:
config yaml:  config/rover/mobilenetv2_aspp_res.yaml
log dir /home/developer/logs/2020-5-01-03:19/
model path None
eval only False
No batchnorm False
----------

Commit hash (training version):  b'5368eed'
----------

Opening config file config/rover/mobilenetv2_aspp_res.yaml
No pretrained directory found.
Copying files to /home/developer/logs/2020-5-01-03:19/ for further reference.
Images from:  /home/taylor/datasets/rover/images/rover_train
Labels from:  /home/taylor/datasets/rover/annotations/rover_train
Inference batch size:  1
Images from:  /home/taylor/datasets/rover/images/rover_test
Labels from:  /home/taylor/datasets/rover/annotations/rover_test
['__add__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'crop', 'crop_param', 'filenames', 'filenamesGt', 'h', 'h_flip', 'images_root', 'jitter', 'labels_root', 'means', 'norm', 'stds', 'subset', 'tensorize_img', 'tensorize_lbl', 'w']
dict_items([(0, 1.0), (1, 1.0), (2, 1.0), (3, 1.0), (4, 1.0), (5, 1.0), (6, 1.0), (7, 1.0), (8, 1.0), (9, 1.0), (10, 1.0), (11, 1.0)])
Original OS:  32
New OS:  8.0
Trying to get backbone weights online from Bonnetal server.
Using pretrained weights from bonnetal server for backbone
[Decoder] os:  4 in:  32 skip: 24 out:  24
[Decoder] os:  2 in:  24 skip: 16 out:  16
[Decoder] os:  1 in:  16 skip: 3 out:  16
Using normalized weights as bias for head.
No path to pretrained, using bonnetal Imagenet backbone weights and random decoder.
Total number of parameters:  2144900
Total number of parameters requires_grad:  2144900
Param encoder  1812800
Param decoder  331896
Param head  204
Training in device:  cuda
[IOU EVAL] IGNORE:  tensor([], dtype=torch.int64)
[IOU EVAL] INCLUDE:  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    trainer.train()
  File "../../tasks/segmentation/modules/trainer.py", line 303, in train
    scheduler=self.scheduler)
  File "../../tasks/segmentation/modules/trainer.py", line 479, in train_epoch
    output = model(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../../tasks/segmentation/modules/segmentator.py", line 102, in forward
    x = self.decoder(x, skips)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../..//tasks/segmentation/decoders/aspp_residual.py", line 83, in forward
    features = mixconv(features)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../../common/layers.py", line 83, in forward
    return x + self.inv_dwise_conv(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 338.00 MiB (GPU 0; 15.89 GiB total capacity; 11.95 GiB already allocated; 324.06 MiB free; 558.73 MiB cached)

```

Here is nvidia-smi when the program is not running. Looks like plenty of RAM available:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P5000        On   | 00000000:08:00.0  On |                  Off |
| 32%   52C    P0    45W / 180W |   2694MiB / 16275MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1635      G   /usr/lib/xorg/Xorg                            97MiB |
|    0      1872      G   /usr/bin/gnome-shell                          53MiB |
|    0      3769      G   /usr/lib/xorg/Xorg                           974MiB |
|    0      3910      G   /usr/bin/gnome-shell                         894MiB |
|    0      6807      G   ...quest-channel-token=7931726709970216186   113MiB |
|    0      7241      G   gnome-control-center                          94MiB |
|    0     10884      G   /usr/bin/vlc                                 110MiB |
|    0     12677      G   ...quest-channel-token=7615775727565811985    56MiB |
|    0     21292      G   ...-token=1B3DA049A377FA772C5604DC206A395E   234MiB |
|    0     23554      G   /usr/lib/firefox/firefox                       1MiB |
|    0     23638      G   /usr/lib/firefox/firefox                       1MiB |
|    0     23666      G   /usr/lib/firefox/firefox                       1MiB |
|    0     27000      G   /usr/lib/firefox/firefox                       1MiB |
|    0     30196      G   kicad                                         46MiB |
+-----------------------------------------------------------------------------+

```

Any help would be appreciated!

**Comment by sequoia-hope** [comment]
Hmm, maybe my image size was a problem. Even with one worker and a batch size of one, my 2560x1440 image size may have been too much. I switched to trying ERFnet and when I used the default of 512x512 it worked. I was able to increase it to 1280x720 with batch and workers of 1. In my end application I only need ~1hz so I thought the high resolution would be cool, but maybe that takes too much RAM? If there's any way to run with 2560x1440 i'd appreciate any tips. Thank you!

**Comment by tano297** [comment]
Hi there,

Yes, for training it will not be possible to use that resolution.
It is important to note that there is a difference between:

```yaml
dataset:
  img_prop:
      width: 2560
      height: 1440
      depth: 3
```
and
```yaml
train:
  crop_prop:
      width: 2560
      height: 1440
```

crop_prop refers to the size of the images during training, and how you crop depends on your dataset and purpose of the application. This is done in the parser. Img_prop, instead, is the inference size. Therefore, if you use 512x512 for the crop_prop, and crop without rescaling you can use 512 for the training and your original resolution for the inference. 

This would, however, reduce the performance during testing, as the network won't get as much context information during training. Therefore I would suggest using something like 1280x720 for the inference, and 512x512 for the training. I've used this same training setup before and it works just fine, and actually infers fast with erfnet or mobilenets. You can then just nearest neighbor upsample the results to your original resolution

**Comment by sequoia-hope** [comment]
Ahhh that makes sense. Thanks for the very helpful explanation, I think I get it now. Well I can improve my settings then, but even with what I had before I am getting some really promising results.

I'll close the issue now, thanks again for the help. Also since I love to share, here's the robot this is for:
https://reboot.love/t/new-cameras-on-rover/

:)

**Comment by tano297** [comment]
Awesome bot! thanks for sharing.
I'm glad to see bonnetal working in the real world, it's its main purpose.
You should get some decent framerates with that AGX. Make sure you run the model with tensorrt
