### ISSUE TITLE
libcublas.so.10, needed by libnvinfer.so, not found 

### ISSUE THREAD

**Issue by BRNKR** [PRBonn/bonnetal#25]
Hey, 

I try to compile the packages without docker (I dont like it and it is also not working for me).

I am running Ubuntu 18.04 with Cuda 10.1, CUDNN8, TensorRT 5.1.5. 

`
/usr/bin/ld: warning: libcublas.so.10, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSetMathMode@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasGetMathMode@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasGetVersion_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasGemmEx@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSetStream_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasHgemmStridedBatched@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSgemm_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasCreate_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasDestroy_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSgemmEx@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasHgemm@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSgemmStridedBatched@libcublas.so.10'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/tobias/src/bonnetal/deploy/devel/.private/bonnetal_segmentation_ros/lib/bonnetal_segmentation_ros/bonnetal_segmentation_node] Error 1
make[1]: *** [CMakeFiles/bonnetal_segmentation_node.dir/all] Error 2
make: *** [all] Error 2

`

**Comment by jbehley** [comment]
I recently also had the Problem with Cuda 10.1. Somehow cublas 10.2 was there, but a cublas in the folder of 10.1 was missing. I then upgraded to CUDA 10.2 and everything works now. Maybe you can also try 10.2.

**Comment by BRNKR** [comment]
will give it a try on monday! thanks

**Comment by BRNKR** [comment]
You were right. Cuda 10.2 with TensorRT6 works, but i get an error when loading model.
https://github.com/PRBonn/bonnetal/issues/26
